### PR TITLE
Fix csrf protection encoding

### PR DESCRIPTION
**Pull request by gaudenz**
This branch fixes two issues I discovered after activating plone.protect with the recent security update.

### CODE REVIEW

**Comment by msom** [comment]
+1

**Comment by msom** [comment]
@MatthewWilkes, @esteele or anyone: Can you have a look into this pull request (and possibly merge/create release)?

**Comment by MatthewWilkes** [comment]
27 days? Oh, I'm sorry @gaudenz! This looks perfectly sensible to me. I was going to say that I'm not the maintainer of this package, but it looks like I was the last one to do a release…

Release incoming.

**Comment by MatthewWilkes** [comment]
@gaudenz @msom 1.0.12 released!

**Comment by msom** [comment]
Great, thanks a lot!

**Comment by gaudenz** [comment]
Thanks !

**Comment by gaudenz** [comment]
@MatthewWilkes Just tried to use your 1.0.12 release, but the at least the tar.gz is broken. It contains paths like parts/omelette/plone/formwidget/contenttree/ which certainly don't belong into a source distribution. Can you please rerelease.

**Comment by MatthewWilkes** [comment]
@gaudenz Hmm, is it just that there are additional things or are some files missing? It shouldn't matter if there are some additional files, but I'll sort out excluding them in future. I don't want to do a new broken release if there are things missing.

**Comment by gaudenz** [comment]
I'm not sure why this happens, but if I add the new version to my
buildout I end up with an egg in the eggs directory which does not
include all files. Everything below plone/formwidgets/contenttree is
missing. If I just install the same egg with easy_install it succeeds.
So this is a bit weird. But when I discovered that the release tarball
also contained additional files, I thought it might be because something
went wrong when releasing.

Gaudenz

**Pull request merged**
