### PR TITLE
feat(frontend) Add Preview pane

### PR DESCRIPTION
**Pull request by do3cc**
- Move hint _Press CTRL to select multiple items_ down to _Add_ and
  _Cancel_ buttons because users did not read it on top.  [saily]
- Adapt PreviewPane to allow writing own Preview Adapters for
  custom preview of own types. A default adapter is still
  available and provides title and description preview for all
  items.  [saily]

### CODE REVIEW

**Comment by do3cc** [comment]
Current status:
- [ ] needs to review if readding translationfiles are really required
- [ ] Is currently failing in our projects, so one of the patch changes wasn't a patch change

**Comment by do3cc** [comment]
@saily

**Comment by do3cc** [comment]
I've mercilessly destroyed history of the configurable_library branch. If you required the changes in the old way, I recreated the branch with its messy history under old_configurable_libraries
Whoever merges this PR when its done, please delete the other branch too

**Comment by jensens** [comment]
I understand correctly:
- This is a Plip for Plone 4.3 only? 
- How is it currently in 5.0?

**Comment by jensens** [comment]
I understand correctly:
- This is a Plip for Plone 4.3 only? 
- How is it currently in 5.0?

**Comment by do3cc** [comment]
I have no idea with Plone 5.0 did it get released already?
Just kidding, but regarding Plone 5.0 this package has seen no changes to become plone 5 compatible.
So this may or may not work with Plone 5

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
