### PR TITLE
Do not automatically filter default pages

### PR DESCRIPTION
**Pull request by pgrunewald**
See issue: https://github.com/plone/plone.formwidget.contenttree/issues/27

### CODE REVIEW

**Comment by pgrunewald** [comment]
Any updates on this topic? Do we need a reviewer?

**Comment by pgrunewald** [comment]
While tests run nicely for 4.3 and 5.0, it fails for 5.1 with:
```
...
Generated script '/home/jenkins/workspace/pull-request-5.1/bin/buildout'.
mr.developer: Creating missing sources dir /home/jenkins/workspace/pull-request-5.1/src.
mr.developer: The package 'plone.formwidget.contenttree' from auto-checkout has no source information.
```

This seems to be a general problem with this package. Any hint, what to do, @jensens?

regards

**Comment by jensens** [comment]
plone.formwidget.contenttree is not part of the core distribution of Plone but is an add-on managed inside the Plone repository. So Jenkins does not know about it. 

@plone/testing-team whats is the official way to deal with this case?

**Comment by gforcada** [comment]
@jensens if it's not part of Plone then it should go with travis or the like? I mean if it's not pulled by buildout.coredev then it can not be tested with our main jobs...

Although if it is on 4.3 and 5.0, it means it got removed by 5.1? Then it should not be even tested on that one...

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
